// module.exports = {
//   DOCTOR_APPROVED: "DOCTOR_APPROVED",
//   DOCTOR_REJECTED: "DOCTOR_REJECTED",

//   APPOINTMENT_REQUESTED: "APPOINTMENT_REQUESTED",
//   APPOINTMENT_CONFIRMED: "APPOINTMENT_CONFIRMED",
//   APPOINTMENT_REJECTED: "APPOINTMENT_REJECTED",
//   APPOINTMENT_CANCELLED_BY_PATIENT: "APPOINTMENT_CANCELLED_BY_PATIENT",
//   APPOINTMENT_CANCELLED_BY_ADMIN: "APPOINTMENT_CANCELLED_BY_ADMIN", 
//   APPOINTMENT_COMPLETED: "APPOINTMENT_COMPLETED",
//   APPOINTMENT_REMINDER: "APPOINTMENT_REMINDER",
//   APPOINTMENT_CANCELLED_BY_DOCTOR: "APPOINTMENT_CANCELLED_BY_DOCTOR",
//   VISIT_SUMMARY_ADDED: "VISIT_SUMMARY_ADDED", 

//   // CERTIFICATE
//   CERTIFICATE_REQUEST_CREATED: "CERTIFICATE_REQUEST_CREATED",
//   CERTIFICATE_APPROVED: "CERTIFICATE_APPROVED",
//   CERTIFICATE_REJECTED: "CERTIFICATE_REJECTED",
//   CERTIFICATE_EXPIRED: "CERTIFICATE_EXPIRED",
//   CERTIFICATE_EXPIRY_REMINDER: "CERTIFICATE_EXPIRY_REMINDER",

// };


module.exports = {
  DOCTOR_APPROVED: "DOCTOR_APPROVED",
  DOCTOR_REJECTED: "DOCTOR_REJECTED",

  APPOINTMENT_REQUESTED: "APPOINTMENT_REQUESTED",
  APPOINTMENT_CONFIRMED: "APPOINTMENT_CONFIRMED",
  APPOINTMENT_REJECTED: "APPOINTMENT_REJECTED",
  APPOINTMENT_CANCELLED_BY_PATIENT: "APPOINTMENT_CANCELLED_BY_PATIENT",
  APPOINTMENT_CANCELLED_BY_ADMIN: "APPOINTMENT_CANCELLED_BY_ADMIN", 
  APPOINTMENT_COMPLETED: "APPOINTMENT_COMPLETED",
  APPOINTMENT_REMINDER: "APPOINTMENT_REMINDER",
  APPOINTMENT_CANCELLED_BY_DOCTOR: "APPOINTMENT_CANCELLED_BY_DOCTOR",
  VISIT_SUMMARY_ADDED: "VISIT_SUMMARY_ADDED", 

  // CERTIFICATE

  CERTIFICATE_APPROVED: "CERTIFICATE_APPROVED",
  CERTIFICATE_REJECTED: "CERTIFICATE_REJECTED",
  CERTIFICATE_EXPIRED: "CERTIFICATE_EXPIRED",
  CERTIFICATE_EXPIRY_REMINDER: "CERTIFICATE_EXPIRY_REMINDER",

};