name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            cd /home/ubuntu/backend_Production

            echo "Fetching latest code..."
            git fetch origin main

            echo "Switching to main branch..."
            git checkout -B main origin/main

            echo "Resetting EC2 code to latest GitHub main..."
            git reset --hard origin/main

            echo "Installing dependencies..."
            npm ci

            echo "Restarting PM2..."
            pm2 restart server --update-env

            echo "Saving PM2 process list..."
            pm2 save

            echo "Current deployed branch:"
            git branch --show-current

            echo "Current deployed commit:"
            git log -1 --oneline

            echo "Deployment completed successfully!"
